apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.app_name}}
  namespace: default
  labels:
    app: app-{{.app_name}}
    name: {{.app_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-{{.app_name}}
      name: {{.app_name}}
  template:
    metadata:
      labels:
        app: app-{{.app_name}}
        name: {{.app_name}}
    spec:
      containers:
        - name: container-{{.app_name}}
          image: {{.image_name}}:{{.build_tag}}
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: service-{{.app_name}}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: app-{{.app_name}}

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.app_name}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - secretName: admin-auto-secret
    hosts:
    - {{.soa_gateway}}
  rules:
    - host: {{.soa_gateway}}
      http:
        paths:
          - path: {{.path_name}}
            pathType: Prefix
            backend:
              serviceName: service-{{.app_name}}
              servicePort: 80
              


